### ISSUE TITLE
Consider YAML as template format

### ISSUE THREAD

**Issue by natenho** [natenho/Mockaco#43]
**Is your feature request related to a problem? Please describe.**
To use the scripting engine on mock templates, most of times there is a need to write an invalid JSON structure, like this:

```json
{
  "request": {
	"method": "PUT",
	"route": "customers/{id}"
  },
  "response": {
	"status": "OK",
	"body": {
	  "url": "<#= Request.Url?.ToString() #>",
	  "customerId": "<#= Request.Route["id"]?.ToString() #>",
	  "acceptHeader": "<#= Request.Header["Content-Type"]?.ToString() #>",
	  "queryString": "<#= Request.Query["dummy"]?.ToString() #>",
	  "requestBodyAttribute": "<#= Request.Body["address"]?[0]?.ToString() #>"
	}
  }
}
```

**Describe the solution you'd like**
[YAML](https://yaml.org/) seems to be suitable alternative to write templates with C# scripts, as it is more permissive on content, like the example bellow, which is a completely valid YAML:

```yaml
---
request:
  method: PUT
  route: customers/{id}
  
response:
  status: OK
  body: |
    {
      "url": "<#= Request.Url?.ToString() #>",
      "customerId": "<#= Request.Route["id"]?.ToString() #>",
      "acceptHeader": "<#= Request.Header["Content-Type"]?.ToString() #>",
      "queryString": "<#= Request.Query["dummy"]?.ToString() #>",
      "requestBodyAttribute": "<#= Request.Body["address"]?[0]?.ToString() #>"
    }
  indented: false
```

There is a C# implementation: [YamlDotNet](https://github.com/aaubry/YamlDotNet)

**Describe alternatives you've considered**
To use [mustache](http://mustache.github.io/) or [handlebars](https://github.com/rexm/Handlebars.Net) templating alternatives would require a DSL to be created. This alternative is not suitable for Mockaco as its proposal is to reduce the learning curve, keeping C# as scripting language.

**Additional context**
There are some disadvantages using YAML:
- It's not so easy to find a YAML formatter ([this one is good](https://onlineyamltools.com/prettify-yaml))
- You can't use tabs to indent the file (😔)
- YAML syntax has more nuances than JSON
- There is no C# project implementing YAML 1.2 spec
